"""The 23 companies of the June/2026 prototype, converted to the v2 model.

English texts come from the prototype. Portuguese texts were written for the seed
(the real ones will come from the companies / Google Forms import). Amounts quoted
in BRL in the prototype were converted at ~5.4 BRL/USD only to fill the demo; in
the real flow the company converts (spec 1, section 2).
"""
from helpers import T, ms, rnd, raised, rev, unsplash, picsum

ORGS = []


def org(**kw):
    ORGS.append(kw)
    return kw


# ---------------------------------------------------------------- Profile A
org(id='imunotera', name='ImunoTera', logo='assets/logos/imunotera.jpg', status='published', public_state='published',
    featured=False, size='startup', city='Ribeirão Preto', state='SP', website='https://www.imunotera.example',
    segments=['biotechnology', 'human_health'], partnership_types=['out_licensing', 'vc'],
    description=T('A ImunoTera desenvolve imunoterapias terapêuticas contra cânceres induzidos por HPV (colo do útero, cabeça e pescoço) e doenças virais emergentes.',
                  'ImunoTera develops therapeutic immunotherapies against HPV-induced cancers (cervical, head & neck) and emerging viral diseases.'),
    cover=unsplash('photo-1579154204601-01588f351e67', 1600, 720),
    card_cover=unsplash('photo-1532187863486-abf9dbad1b69', 900, 500),
    gallery=[
        (unsplash('photo-1579154204601-01588f351e67', 700, 700), T('Laboratório', 'Laboratory')),
        (unsplash('photo-1587854692152-cbe660dbde88', 700, 700), T('Produto', 'Product')),
        (unsplash('photo-1579165466741-7f35e4755660', 700, 700), T('Equipe', 'Team')),
        (unsplash('photo-1532187863486-abf9dbad1b69', 700, 700) + '&crop=faces', T('Estudos', 'Trials')),
    ],
    leadership=[
        dict(name='Ana Ribeiro', role=T('CEO e cofundadora', 'CEO & Co-founder'), experience=T('15 anos em imunologia de tumores; PhD pela USP.', '15 years in tumor immunology; PhD from USP.')),
        dict(name='Carlos Menezes', role=T('Diretor científico', 'Chief Scientific Officer'), experience=T('Ex-pesquisador do Instituto Butantan, 40 artigos publicados.', 'Former researcher at Instituto Butantan, 40 published papers.')),
    ],
    projects=[dict(
        id='imunotera-terah7', type='A',
        segment=T('Imunoterapia — Oncologia / cânceres induzidos por HPV', 'Immunotherapy — Oncology / HPV-induced cancers'),
        trl=5, regulatory_phase='preclinical',
        lead_product_name='TERAH-7',
        lead_product_moa=T('Vacina terapêutica capaz de tratar a doença estabelecida e induzir memória imunológica duradoura contra células tumorais.',
                           'Therapeutic vaccine capable of treating established disease while inducing long-lasting immunological memory against tumor cells.'),
        pipeline=[('TERAVID-19', T('Imunoterapia para SARS-CoV-2', 'SARS-CoV-2 immunotherapy')),
                  ('A9Z', T('Imunoterapia para ZIKV/DENV', 'ZIKV/DENV immunotherapy')),
                  ('IMT-075', T('Indicação adicional em definição', 'Additional indication being defined'))],
        patents_filed=T('PCT/BR2024/050376 (WO2025039059A1) em exame no BR, CA, CL, CO, MX, EC, US e EP. PCT adicional WO2025107050A1 (A9Z, BR e US), também em exame.',
                        'PCT/BR2024/050376 (WO2025039059A1) filed and under examination in BR, CA, CL, CO, MX, EC, US and EP. Additional PCT WO2025107050A1 (A9Z, BR and US), also under examination.'),
        fto='in_progress',
        milestones=[ms(2026, s=2, pt='Estudos pré-clínicos toxicológicos e produção de lote clínico GMP', en='Toxicological pre-clinical studies and GMP clinical batch production'),
                    ms(2028, s=1, pt='Estudo clínico de Fase I/II (Série A)', en='Phase I/II clinical study (Series A)')],
        rounds=[rnd('seed', ms(2026, s=2), 1000000, 'Lote clínico GMP', 'GMP clinical batch'),
                rnd('series_a', ms(2028, s=1), 3000000, 'Estudo clínico de Fase I/II', 'Phase I/II clinical trial')],
        use_of_funds=T('Fabricação de lote clínico GMP na fase Seed; estudo de Fase I/II na Série A.',
                       'GMP clinical batch manufacturing in the Seed phase; Phase I/II trial in the Series A.'),
        raised=[raised('fapesp', 1110000), raised('cnpq', 57000), raised('other', 22000, 'Catalisa ICT'),
                raised('award', 33000), raised('angel', 39000), raised('donation', 19000)],
        gtm_models=['out_licensing'],
        gtm_text=T('Licenciamento para parceiros farmacêuticos globais.', 'Out-licensing to global pharmaceutical partners.'),
        target_markets=['brazil', 'north_america', 'europe', 'latin_america'],
    )])

org(id='heptech', name='Heptech Biotech', status='returned', public_state='provisional',
    segments=['biotechnology', 'pharmaceutical'], partnership_types=['out_licensing'],
    description=T('A Heptech desenvolve heparina de baixo peso molecular (HBPM) de origem bovina como alternativa à suína, reduzindo a vulnerabilidade da cadeia global de heparina.',
                  'Heptech develops bovine-derived low molecular weight heparin (LMWH) as a non-porcine alternative, addressing the vulnerability of the global heparin supply chain.'),
    projects=[dict(
        id='heptech-lmwh', type='A',
        segment=T('Anticoagulante — Heparina bovina de baixo peso molecular', 'Anticoagulant — Bovine low molecular weight heparin'),
        trl=5, regulatory_phase='preclinical', lead_product_name='Bovine LMWH',
        lead_product_moa=T('Mecanismo anticoagulante que inibe a coagulação sanguínea, voltado a mercados onde a heparina suína é restrita ou indisponível.',
                           'Anticoagulant mechanism inhibiting blood coagulation, targeting markets where porcine heparin is restricted or unavailable.'),
        pipeline=[('UFH bovina', T('Heparina não fracionada com atividade equivalente ao padrão suíno', 'Non-fractionated heparin with activity equivalent to the porcine standard'))],
        patents_filed=T('PCT/BR2024/050460 pendente.', 'PCT/BR2024/050460 pending.'),
        patents_granted=T('US 12,485,137B2; BR 112021015794-8.', 'US 12,485,137B2; BR 112021015794-8.'),
        milestones=[ms(2027, m=6, pt='Conclusão da fase pré-clínica e preparação da submissão de IND', en='Completion of the pre-clinical phase and IND submission preparation')],
        rounds=[rnd('series_a', ms(2027, s=1), 3000000, 'Toxicologia e farmacologia pré-clínicas', 'Pre-clinical toxicology and pharmacology')],
        use_of_funds=T('Estudos pré-clínicos de toxicologia e farmacologia; submissões regulatórias.',
                       'Pre-clinical toxicology and pharmacology studies; regulatory submissions.'),
        raised=[raised('finep', 1000000), raised('other', 1000000, 'B2B partner')],
        gtm_models=['out_licensing'], gtm_text=T('Licenciamento.', 'Out-licensing.'),
        target_markets=['north_america', 'asia'],
    )])

org(id='krabs', name='KRABS', status='provisional', public_state='provisional',
    segments=['biotechnology'], partnership_types=['out_licensing'],
    description=T('A KRABS desenvolve um tratamento tópico inovador para dermatite atópica com um anticorpo próprio que inibe a KLK7, enzima associada à descamação da pele.',
                  'KRABS develops a novel topical treatment for Atopic Dermatitis using a proprietary antibody that inhibits KLK7, an enzyme associated with skin desquamation.'),
    projects=[dict(
        id='krabs-klk7', type='A',
        segment=T('Dermatologia — Tratamento tópico para dermatite atópica', 'Dermatology — Topical treatment for Atopic Dermatitis'),
        trl=5, regulatory_phase='preclinical', lead_product_name='Anti-KLK7 topical antibody',
        lead_product_moa=T('Anticorpo tópico inibidor de KLK7 — alternativa sem corticoide para uma das doenças de pele mais prevalentes do mundo.',
                           'Topical KLK7-inhibitor antibody — steroid-free alternative for one of the world’s most prevalent skin conditions.'),
        pipeline=[('Glyphosate rapid test', T('Método portátil de detecção rápida de glifosato', 'Portable rapid glyphosate detection method')),
                  ('CAR-T', T('Terapia CAR-T para câncer de próstata', 'CAR-T therapy for prostate cancer'))],
        patents_filed=T('BR 102020009679-6 A2 (Brasil, pendente); EP 4 151 657 A1 (Europa, pendente); WO 2021/226695 A1 (PCT).',
                        'BR 102020009679-6 A2 (Brazil, pending); EP 4 151 657 A1 (Europe, pending); WO 2021/226695 A1 (PCT).'),
        patents_granted=T('US 12,590,170 B2.', 'US 12,590,170 B2.'), fto='yes',
        milestones=[ms(2026, s=2, pt='Estruturação da rodada de captação', en='Fundraising round structuring'),
                    ms(2027, s=2, pt='Próximo marco regulatório', en='Next regulatory milestone')],
        rounds=[rnd('seed', ms(2026, s=2), 1000000, 'Avanço pré-clínico', 'Pre-clinical advancement')],
        use_of_funds=T('Avanço pré-clínico e submissões regulatórias.', 'Pre-clinical advancement and regulatory submissions.'),
        raised=[raised('fapesp', 270000), raised('finep', 269000)],
        revenue=rev(30000, 2025),
        gtm_models=['out_licensing'], gtm_text=T('Licenciamento.', 'Out-licensing.'),
        target_markets=['brazil', 'north_america', 'europe'],
    )])

org(id='cellertz', name='Cellertz Bio', status='provisional', public_state='provisional',
    segments=['biotechnology', 'human_health'], partnership_types=['out_licensing', 'co_development', 'vc'],
    description=T('A Cellertz Bio desenvolve o CellBiTE (CLZ-06X), um mRNA que codifica um engajador biespecífico de células T anti-CD19/CD3 para leucemia linfoide aguda. A abordagem in vivo evita a complexidade e o custo de fabricação dos BiTEs proteicos tradicionais.',
                  'Cellertz Bio develops CellBiTE (CLZ-06X), an mRNA encoding a bispecific T-cell engager targeting CD19/CD3 for acute lymphoid leukemia. The in vivo approach avoids the complexity and manufacturing cost of traditional protein-based BiTE production.'),
    projects=[dict(
        id='cellertz-cellbite', type='A',
        segment=T('Oncologia / Hematologia — Engajador biespecífico de células T por mRNA (BiKE)', 'Oncology / Hematology — mRNA bispecific T-cell engager (BiKE)'),
        trl=3, regulatory_phase='preclinical', lead_product_name='CellBiTE (CLZ-06X)',
        lead_product_moa=T('Engajador biespecífico anti-CD19/anti-CD3 codificado por mRNA. Conecta células T (CD3) e células tumorais (CD19), provocando lise tumoral seletiva.',
                           'mRNA-encoded anti-CD19/anti-CD3 bispecific T-cell engager. Bridges T cells (CD3) and tumor cells (CD19), triggering selective tumor lysis.'),
        pipeline=[('CLZ-02X', T('CAR+BiKE in vivo para mieloma múltiplo', 'In vivo CAR+BiKE for multiple myeloma')),
                  ('CLZ-01X', T('Linfoma', 'Lymphoma'))],
        fto='in_progress',
        milestones=[ms(2026, m=10, pt='Prova de conceito in vivo (PoC)', en='In vivo proof of concept (PoC)')],
        rounds=[rnd('pre_seed', ms(2026, s=2), 1800000, 'PoC in vivo e conclusão do pré-seed', 'In vivo PoC and pre-seed completion')],
        use_of_funds=T('Estudos de PoC in vivo e conclusão da rodada pré-seed (USD 600 mil já captados; USD 1,2 milhão em aberto).',
                       'In vivo PoC studies and completion of the pre-seed round (USD 600K already raised; USD 1.2M outstanding).'),
        raised=[raised('vc', 600000), raised('other', 740000, 'Partner project')],
        gtm_models=['out_licensing', 'co_development'], gtm_text=T('Licenciamento e co-desenvolvimento.', 'Out-licensing and co-development.'),
        target_markets=['north_america', 'europe', 'asia', 'oceania'],
    )])

org(id='aptah', name='Aptah Bio', status='provisional', public_state='provisional',
    segments=['biotechnology'], partnership_types=['vc'],
    description=T('A Aptah Bio desenvolve o APT20TTMG, molécula sintética de DNA de fita simples que corrige a disfunção do complexo U1 snRNP, essencial para o splicing do pré-mRNA, com ampla aplicação potencial em oncologia.',
                  'Aptah Bio develops APT20TTMG, a synthetic single-stranded DNA molecule that corrects the dysfunction of the U1 snRNP complex, essential for pre-mRNA splicing, with broad potential application in oncology.'),
    projects=[dict(
        id='aptah-apt20', type='A',
        segment=T('Oncologia — Aptâmero de DNA terapêutico', 'Oncology — DNA aptamer therapeutic'),
        trl=4, regulatory_phase='preclinical', lead_product_name='APT20TTMG',
        lead_product_moa=T('Corrige a disfunção do complexo U1 snRNP, restaurando a expressão gênica normal em células tumorais.',
                           'Corrects U1 snRNP complex dysfunction, restoring normal gene expression in cancer cells.'),
        patents_filed=T('PCT pendente em EP, JP, CN e US ("Polynucleotide compositions and methods for treatment of cancer" e "...for gene expression regulation").',
                        'PCT pending in EP, JP, CN and US ("Polynucleotide compositions and methods for treatment of cancer" and "...for gene expression regulation").'),
        patents_granted=T('Patente concedida e ativa nos EUA.', 'Patent granted and active in the US.'),
        milestones=[ms(2028, m=4, pt='Próximo marco regulatório', en='Next regulatory milestone')],
        rounds=[rnd('series_a', ms(2027, s=1), 20000000, 'Pacote IND e preparação da Fase I', 'IND package and Phase I preparation')],
        use_of_funds=T('Pacote IND, conclusão do pré-clínico e preparação da Fase I.', 'IND package, pre-clinical completion and Phase I preparation.'),
        raised=[raised('other', 8890000, 'Grants, angels and VC')],
        gtm_models=['direct_sales'], gtm_text=T('Entrada direta no mercado.', 'Direct market entry.'),
        target_markets=['brazil', 'north_america'],
    )])

org(id='wecare', name='Wecare Skin', status='filling', public_state='provisional',
    segments=['pharmaceutical', 'human_health'], partnership_types=['out_licensing'],
    description=T('A Wecare Skin desenvolve um composto tópico próprio semelhante a corticoide, com atividade anti-inflamatória para dermatite e psoríase, sem os efeitos adversos dos corticoides convencionais.',
                  'Wecare Skin develops a proprietary corticoid-like topical compound with anti-inflammatory activity for dermatitis and psoriasis, without the adverse effects of conventional corticosteroids.'),
    projects=[dict(
        id='wecare-topical', type='A',
        segment=T('Dermatologia / Anti-inflamatório — Composto tópico semelhante a corticoide', 'Dermatology / Anti-inflammatory — Corticoid-like topical compound'),
        trl=5, regulatory_phase='preclinical', lead_product_name='WCS-01',
        lead_product_moa=T('Ação anti-inflamatória para dermatite e psoríase, como substituto de corticoides.',
                           'Anti-inflammatory action for dermatitis and psoriasis, as a corticosteroid substitute.'),
        pipeline=[('WCS-02', T('Atrofia vaginal', 'Vaginal atrophy')), ('WCS-03', T('Cicatrização pós-parto', 'Post-partum healing')),
                  ('WCS-04', T('Cicatrização pós-cirúrgica', 'Post-surgical healing'))],
        patents_filed=T('7 pedidos de patente depositados no Brasil.', '7 patent applications filed in Brazil.'), fto='yes',
        milestones=[ms(2027, s=1, pt='Início do estudo clínico de Fase I', en='Phase I clinical study initiation')],
        rounds=[rnd('series_a', ms(2026, s=2), 6000000, 'Estudo de Fase I', 'Phase I trial'),
                rnd('series_b', ms(2028, s=2), 24000000, 'Fases II e III', 'Phases II and III')],
        use_of_funds=T('Estudo clínico de Fase I, submissões regulatórias e escalonamento.', 'Phase I clinical trial, regulatory submissions and scale-up.'),
        raised=[raised('finep', 1140000), raised('fapesp', 347000), raised('vc', 597000), raised('angel', 539000)],
        revenue=rev(578000, 2025),
        gtm_models=['out_licensing'], gtm_text=T('Licenciamento.', 'Out-licensing.'),
        target_markets=['brazil', 'europe', 'latin_america'],
    )])

org(id='nintx', name='Nintx', status='in_review', public_state='published', featured=True, size='startup',
    city='São Paulo', state='SP', website='https://www.nintx.example',
    segments=['biotechnology', 'human_health'], partnership_types=['vc', 'co_development'],
    description=T('A Nintx desenvolve um ingrediente de origem natural para o tratamento da doença inflamatória intestinal (DII), com abordagem multimecanística, apoiada pelas plataformas próprias xGIbiomics® e GAIApath™ de simulação do microbioma e descoberta de biomarcadores com IA.',
                  'Nintx develops a nature-derived ingredient for IBD treatment with a multi-mechanistic approach, supported by its proprietary xGIbiomics® and GAIApath™ platforms for microbiome simulation and AI-driven biomarker discovery.'),
    leadership=[dict(name='Rafael Duarte', role=T('CEO', 'CEO'), experience=T('Fundador de duas biotechs; ex-diretor de P&D em farmacêutica nacional.', 'Founder of two biotechs; former R&D director at a Brazilian pharma.'))],
    projects=[dict(
        id='nintx-ntx06', type='A',
        segment=T('Imunologia GI — Doença inflamatória intestinal (DII)', 'GI Immunology — Inflammatory Bowel Disease (IBD)'),
        trl=5, regulatory_phase='phase_1', lead_product_name='NTX-06',
        lead_product_moa=T('Reduz infiltrados imunológicos e citocinas pró-inflamatórias, com modulação positiva do microbioma intestinal. PoC clínica prevista para junho de 2027.',
                           'Reduces immunological infiltrates and pro-inflammatory cytokines, with positive gut microbiome modulation. Clinical PoC expected June 2027.'),
        pipeline=[('NTX-03', T('Molécula sintética para regeneração do músculo cardíaco, com validação biofísica e celular concluída', 'Synthetic molecule for cardiac muscle regeneration, with biophysical and cellular validation already completed'))],
        patents_filed=T('PBTX-01 (BR10 2026 008578-2); PBTX-02 (BR10 2025 007846-5).', 'PBTX-01 (BR10 2026 008578-2); PBTX-02 (BR10 2025 007846-5).'),
        patents_granted=T('xGIbiomics® (BR202022013346-3); Mini xGIbiomics® (BR202023024796-5).', 'xGIbiomics® (BR202022013346-3); Mini xGIbiomics® (BR202023024796-5).'),
        fto='yes',
        milestones=[ms(2027, m=6, pt='Conclusão da PoC clínica', en='Completion of clinical PoC'),
                    ms(2027, s=2, pt='Lançamento da rodada Série B', en='Series B round launch')],
        rounds=[rnd('series_b', ms(2027, s=2), 30000000, 'Fases I/II e escalonamento comercial', 'Phase I/II and commercial scale-up')],
        use_of_funds=T('Estudos de Fase I/II, submissões regulatórias e escalonamento comercial.', 'Phase I/II studies, regulatory submissions and commercial scale-up.'),
        raised=[raised('vc', 13000000), raised('other', 5000000, 'Grants')],
        gtm_models=['partnership_distribution'],
        gtm_text=T('Parcerias com fundos de venture capital e programas de fomento.', 'Partnerships with venture capital funds and grant programs.'),
        target_markets=['brazil', 'north_america', 'europe', 'latin_america', 'asia', 'oceania'],
    )])

org(id='mirscience', name='Mirscience Therapeutics', status='provisional', public_state='provisional',
    segments=['biotechnology'], partnership_types=['out_licensing'],
    description=T('Terapia de RNA para sarcopenia (atrofia muscular). O produto principal silencia genes responsáveis pela atrofia muscular por interferência de RNA.',
                  'RNA therapy targeting sarcopenia (muscle atrophy). The lead product silences genes responsible for muscle atrophy via RNA interference.'),
    projects=[dict(
        id='mirscience-mt01', type='A',
        segment=T('Terapias de RNA — Sarcopenia', 'RNA Therapeutics — Sarcopenia'),
        trl=4, regulatory_phase='preclinical', lead_product_name='MT-01',
        lead_product_moa=T('Silenciamento de genes da atrofia muscular por interferência de RNA.', 'Silencing of muscle atrophy genes via RNA interference.'),
        pipeline=[('MT-02', T('Sarcopenia em pacientes obesos', 'Sarcopenia in obese patients'))],
        patents_filed=T('Patentes depositadas no Brasil, Europa e Estados Unidos.', 'Patents filed in Brazil, Europe and the United States.'),
        milestones=[ms(2027, s=1, pt='Autorização da ANVISA para Fase I (submissão de IND)', en='ANVISA Phase I authorization (IND submission)')],
        rounds=[rnd('seed', ms(2026, s=2), 5000000, 'IND e Fase I', 'IND and Phase I')],
        use_of_funds=T('Submissão de IND e estudo clínico de Fase I.', 'IND submission and Phase I clinical trial.'),
        raised=[raised('other', 222000)],
        gtm_models=['out_licensing'], gtm_text=T('Licenciamento.', 'Out-licensing.'),
        target_markets=['brazil', 'north_america', 'europe', 'asia'],
    )])

org(id='biocase', name='Biocase Group', status='provisional', public_state='provisional',
    segments=['pharmaceutical', 'human_health'], partnership_types=['vc'],
    description=T('Formulação de psilocibina natural para transtorno depressivo maior, alcoolismo, tabagismo e transtornos de impulso, com ação nos receptores 5-HT2A do córtex pré-frontal e efeito de 3 a 6 meses por dose.',
                  'Natural psilocybin formulation targeting major depressive disorder, alcoholism, tobacco addiction and impulse disorders, acting on 5-HT2A receptors in the prefrontal cortex, with effects lasting 3 to 6 months per dose.'),
    projects=[dict(
        id='biocase-psilo', type='A',
        segment=T('Psicodélicos / SNC — Psilocibina natural para depressão, dependência e transtornos de impulso', 'Psychedelics / CNS — Natural psilocybin for depression, addiction and impulse disorders'),
        trl=5, regulatory_phase='preclinical', lead_product_name='Natural psilocybin',
        lead_product_moa=T('Indicação psiquiátrica/SNC. Agonismo 5-HT2A no córtex pré-frontal, reiniciando a rede de modo padrão.',
                           'CNS/psychiatric indication. 5-HT2A agonism in the prefrontal cortex, resetting the default mode network.'),
        pipeline=[('PsiloCINE', T('Formulação sublingual de psilocina', 'Sublingual psilocin formulation'))],
        patents_filed=T('Pedido de patente de processo depositado no Brasil.', 'Process patent application filed in Brazil.'),
        milestones=[ms(2026, m=8, pt='Petição à ANVISA para estudo de Fase I / registro', en='ANVISA petition for Phase I study / registration')],
        rounds=[rnd('series_a', ms(2026, s=2), 6000000, 'Estudo de Fase I', 'Phase I study')],
        use_of_funds=T('Estudo clínico de Fase I pela via regulatória da ANVISA para substâncias controladas.', 'Phase I clinical study under ANVISA’s regulatory pathway for controlled substances.'),
        raised=[raised('other', 1500000, 'Family office and grants')],
        revenue=rev(400000, 2025),
        gtm_models=['direct_sales'],
        gtm_text=T('Mercado regulado de medicamentos de controle especial.', 'Regulated market for special-control medications.'),
        target_markets=['brazil'],
    )])

org(id='celluris', name='Celluris', status='provisional', public_state='provisional',
    segments=['biotechnology', 'human_health'], partnership_types=['out_licensing'],
    description=T('Plataforma própria de CAR-T para tumores sólidos, com arquitetura de dois módulos que mira o antígeno tumoral e sequestra uma proteína do microambiente tumoral, superando um mecanismo-chave de resistência.',
                  'Proprietary CAR-T platform for solid tumors, with a dual-module architecture that targets the tumor antigen and sequesters a tumor microenvironment protein, overcoming a key resistance mechanism.'),
    projects=[dict(
        id='celluris-cart', type='A',
        segment=T('Terapia celular e gênica — CAR-T para tumores sólidos', 'Cell and gene therapy — CAR-T for solid tumors'),
        trl=5, regulatory_phase='preclinical', lead_product_name='Dual-module CAR-T',
        lead_product_moa=T('Módulo direcionado ao tumor + modulação do microambiente pelo sequestro de uma proteína imunossupressora.',
                           'Tumor-targeted module + microenvironment modulation via sequestration of an immunosuppressive protein.'),
        pipeline=[('CAR-T lung', T('Câncer de pulmão', 'Lung cancer')), ('CAR-T ovarian', T('Câncer de ovário', 'Ovarian cancer'))],
        patents_filed=T('EUA: 1 continuação em análise. Japão: 1 em análise. Europa: em análise.', 'US: 1 continuation under review. Japan: 1 under review. Europe: under review.'),
        patents_granted=T('EUA: US 12,491,247. Japão: 1 concedida.', 'US: US 12,491,247. Japan: 1 granted.'), fto='yes',
        milestones=[ms(2027, s=2, pt='Conclusão do pacote IND e submissão à FDA e à ANVISA, visando a Fase I', en='Completion of the IND package and submission to FDA and ANVISA, targeting Phase I')],
        rounds=[rnd('series_a', ms(2027, s=1), 20000000, 'Pacote IND e Fase I', 'IND package and Phase I')],
        use_of_funds=T('Preparação do pacote IND, submissões à FDA/ANVISA e estudo de Fase I.', 'IND package preparation, FDA/ANVISA submissions and Phase I study.'),
        raised=[raised('vc', 3000000)],
        gtm_models=['out_licensing'], gtm_text=T('Licenciamento.', 'Out-licensing.'),
        target_markets=['brazil', 'north_america', 'latin_america'],
    )])

# ---------------------------------------------------------------- Profile B
org(id='qnity', name='Qnity', logo='assets/logos/qnity.png', status='provisional', public_state='provisional',
    segments=['devices_diagnostics'], partnership_types=['vc', 'market_distribution'],
    description=T('A Qnity desenvolve uma plataforma de instrumentação científica baseada em eletroquímica quântica para análise em tempo real de interações moleculares, convertidas em sinais eletroquímicos ultrassensíveis.',
                  'Qnity is developing a scientific instrumentation platform based on quantum electrochemistry for real-time analysis of molecular interactions, translating them into ultrasensitive electrochemical signals.'),
    projects=[dict(
        id='qnity-platform', type='B',
        platform_type=T('Instrumentação científica — Biossensoriamento por eletroquímica quântica', 'Scientific instrumentation — Quantum electrochemistry biosensing'),
        maturity='pre_operational',
        platform_description=T('Equipamento e interfaces moleculares próprias que medem cinética de ligação em tempo real, sem marcação.',
                               'Proprietary equipment and molecular interfaces that measure binding kinetics in real time, label-free.'),
        technology_tags=['electrochemistry', 'biosensors'],
        technology_text=T('Eletroquímica quântica; eletroquímica avançada; biossensores eletroquímicos; interfaces moleculares próprias; nanomateriais.',
                          'Quantum electrochemistry; advanced electrochemistry; electrochemical biosensors; proprietary molecular interfaces; nanomaterials.'),
        business_models=['equipment', 'consumables', 'service'],
        business_model_text=T('Venda de equipamentos + consumíveis + serviços especializados. Venda direta ou comodato com receita recorrente de consumíveis.',
                              'Equipment sales + consumables + specialized services. Direct sale or placement model with recurring consumables revenue.'),
        traction=T('Interações e parcerias em desenvolvimento com farmacêuticas, instituições de pesquisa e outros atores de ciências da vida.',
                   'Interactions and partnerships in development with pharmaceutical companies, research institutions and other life sciences players.'),
        competitive_edge=T('Transdução ultrassensível de sinal molecular por eletroquímica quântica — análise de cinética de ligação sem marcação nem preparo complexo de amostra.',
                           'Ultra-sensitive molecular signal transduction via quantum electrochemistry — binding kinetics analysis without labeling or complex sample preparation.'),
    )])

org(id='peptidus', name='Peptidus Biotech', status='provisional', public_state='provisional',
    segments=['biotechnology', 'animal_health'], partnership_types=['vc', 'out_licensing'],
    description=T('A plataforma LAIKA, da Peptidus Biotech, usa IA/ML para projetar e validar novos peptídeos terapêuticos para saúde animal, segmento historicamente pouco atendido pelas plataformas de descoberta de fármacos.',
                  'Peptidus Biotech’s LAIKA platform uses AI/ML to design and validate new therapeutic peptides for animal health, a segment historically underserved by drug-discovery platforms.'),
    projects=[dict(
        id='peptidus-laika', type='B',
        platform_type=T('IA/ML — Descoberta de peptídeos terapêuticos para saúde animal', 'AI/ML — Therapeutic peptide discovery for animal health'),
        maturity='partially_operational',
        platform_description=T('LAIKA: plataforma de descoberta de peptídeos que cobre do desenho in silico à validação, para licenciamento a farmacêuticas veterinárias.',
                               'LAIKA: a peptide-discovery platform covering in silico design through validation, for licensing to veterinary pharma companies.'),
        technology_tags=['ai_ml'],
        technology_text=T('IA/ML (modelos preditivos multicamada), modelagem e dinâmica molecular, base própria de peptídeos, bioinformática estrutural.',
                          'AI/ML (multi-layer predictive models), molecular modeling and dynamics, proprietary peptide database, structural bioinformatics.'),
        business_models=['licensing'],
        business_model_text=T('Licenciamento B2B de PI: cria e valida peptídeos nas etapas de descoberta e licencia os ativos a farmacêuticas e biotechs.',
                              'B2B IP licensing: creates and validates peptides through the drug-discovery stages and licenses the assets to pharma/biotech companies.'),
        traction=T('Pré-receita. NDAs assinados e discussões técnicas ativas com grandes farmacêuticas de saúde animal. Primeiro licenciamento previsto para 2026, após o fechamento da rodada Seed.',
                   'Pre-revenue. Signed NDAs and active technical discussions with major animal-health pharma companies. First licensing expected in 2026, after the Seed round closes.'),
        revenue=rev(None, None, pre=True),
        competitive_edge=T('Foco em peptídeos para saúde animal — lacuna nas plataformas globais de descoberta com IA. Base de dados própria e arquitetura preditiva multicamada.',
                           'Focus on animal-health peptides — a gap in global AI drug-discovery platforms. Proprietary database and multi-layer predictive architecture.'),
    )])

org(id='sante', name='Sante Science', status='provisional', public_state='provisional',
    segments=['biotechnology', 'animal_health'], partnership_types=['co_development', 'out_licensing'],
    description=T('Plataforma de biotecnologia que usa fermentação microbiana própria para produzir ingredientes pós-bióticos com composição bioativa complexa e atividade multimodal, para saúde animal e nutrição humana.',
                  'Biotechnology platform using proprietary microbial fermentation to produce postbiotic ingredients with complex bioactive composition and multimodal activity, for animal health and human nutrition.'),
    projects=[dict(
        id='sante-postbiotics', type='B',
        platform_type=T('Biotecnologia de fermentação — Ingredientes pós-bióticos para saúde animal e humana', 'Fermentation biotechnology — Postbiotic ingredients for animal and human health'),
        maturity='pre_operational',
        platform_description=T('Processo próprio de fermentação microbiana para gerar pós-bióticos com múltiplos compostos bioativos.',
                               'Proprietary microbial fermentation process generating postbiotics with multiple bioactive compounds.'),
        technology_tags=['fermentation'],
        technology_text=T('Biotecnologia microbiana; fermentação de precisão; engenharia metabólica; desenvolvimento de pós-bióticos; metabolômica.',
                          'Microbial biotechnology; precision fermentation; metabolic engineering; postbiotic development; metabolomics.'),
        business_models=['licensing', 'service'],
        business_model_text=T('Vendas B2B a empresas de saúde animal, nutrição e farmacêuticas. Receita de venda de ingredientes, co-desenvolvimento e licenciamento.',
                              'B2B sales to animal health, nutrition and pharmaceutical companies. Revenue from ingredient sales, co-development and licensing.'),
        traction=T('4 cartas de intenção assinadas com empresas brasileiras de saúde e nutrição animal; 1 carta com empresa internacional.',
                   '4 LOIs signed with Brazilian animal-health and nutrition companies; 1 LOI with an international company.'),
        competitive_edge=T('Processo próprio de fermentação que gera pós-bióticos com composição bioativa complexa e atividade multimodal, diferente das abordagens de composto único.',
                           'Proprietary fermentation process generating postbiotics with complex bioactive composition and multimodal activity — differentiated from single-compound approaches.'),
    )])

org(id='microforge', name='Micro Forge Biotech', status='provisional', public_state='provisional',
    segments=['biotechnology', 'biodiversity_bioeconomy'], partnership_types=['out_licensing', 'co_development'],
    description=T('A Micro Forge desenvolve plataformas biotecnológicas para produzir moléculas de alto valor por microrganismos, com foco em desenvolvimento de linhagens, otimização de fermentação e purificação.',
                  'Micro Forge develops biotechnology platforms for producing high-value molecules via microorganisms, focused on strain development, fermentation optimization and downstream purification.'),
    projects=[dict(
        id='microforge-synbio', type='B',
        platform_type=T('Biologia sintética / Engenharia metabólica — Produção de moléculas de alto valor', 'Synthetic biology / Metabolic engineering — High-value molecule production'),
        maturity='pre_operational',
        platform_description=T('Plataformas de linhagens microbianas e processos de fermentação para moléculas de alto valor agregado.',
                               'Microbial strain and fermentation-process platforms for high-value molecules.'),
        technology_tags=['fermentation', 'genomics'],
        technology_text=T('Bioinformática; biologia sintética; engenharia metabólica; biologia molecular; microbiologia; engenharia de fermentação.',
                          'Bioinformatics; synthetic biology; metabolic engineering; molecular biology; microbiology; fermentation engineering.'),
        business_models=['licensing', 'service'],
        business_model_text=T('Licenciamento de plataformas + P&D sob contrato (modelo PD&I). Clientes recentes no setor sucroenergético.',
                              'IP licensing of platforms + contract R&D (PD&E model). Recent clients in the sugarcane energy sector.'),
        traction=T('Clientes atuais no setor sucroenergético.', 'Current clients in the sugarcane sector.'),
        revenue=rev(20000, 2025),
        competitive_edge=T('Equipe multidisciplinar que integra biologia sintética, biologia molecular, engenharia metabólica e fermentação — do desenho do gene à produção.',
                           'Multidisciplinary team integrating synthetic biology, molecular biology, metabolic engineering and fermentation — from gene design to production.'),
    )])

org(id='techtrials', name='Techtrials', logo='assets/logos/techtrials.png', status='published', public_state='published',
    featured=False, size='startup', city='São Paulo', state='SP', website='https://www.techtrials.example',
    segments=['human_health', 'other'], partnership_types=['vc', 'market_distribution'],
    description=T('A Techtrials é uma plataforma de inteligência em saúde baseada em Real-World Evidence, dados clínicos e epidemiológicos, analytics avançado e IA. Integra dados de várias fontes e gera insights estratégicos para farmacêuticas, operadoras, hospitais e reguladores.',
                  'Techtrials is a health intelligence platform built on Real-World Evidence, clinical and epidemiological data, advanced analytics and AI. It integrates data from multiple sources and generates strategic insights for pharma, payers, hospitals and regulators.'),
    projects=[dict(
        id='techtrials-rwe', type='B',
        platform_type=T('Real-World Evidence — Inteligência em saúde com IA', 'Real-World Evidence — AI-powered health intelligence'),
        maturity='fully_operational',
        platform_description=T('Plataforma de dados e analytics que integra fontes clínicas e epidemiológicas com estrutura de nível regulatório.',
                               'Data and analytics platform integrating clinical and epidemiological sources with a regulatory-grade structure.'),
        technology_tags=['ai_ml'],
        technology_text=T('Inteligência artificial; machine learning; ciência de dados em saúde; Real-World Evidence; epidemiologia comparada; NLP; analytics clínico.',
                          'Artificial intelligence; machine learning; health data science; Real-World Evidence; comparative epidemiology; NLP; clinical analytics.'),
        business_models=['saas', 'service'],
        business_model_text=T('B2B — assinatura e projetos de analytics para farmacêuticas, hospitais e sistemas de saúde.',
                              'B2B — subscription and project-based analytics for pharma, hospitals and health systems.'),
        traction=T('Mais de 50 clientes ativos, entre eles Sanofi, Ferring, Amgen e redes hospitalares.',
                   '50+ active clients including Sanofi, Ferring, Amgen and hospital networks.'),
        revenue=rev(400000, 2025),
        competitive_edge=T('Integração de dados de saúde de várias fontes com estrutura de nível regulatório; diversidade epidemiológica da população brasileira; camada combinada de analytics clínico e epidemiológico.',
                           'Multi-source health data integration with regulatory-grade structure; epidemiological diversity of the Brazilian population; combined clinical and epidemiological analytics layer.'),
        rounds=[rnd('series_a', ms(2027, s=1), 4000000, 'Expansão internacional', 'International expansion')],
    )])

org(id='vesper', name='Vesper Biotechnologies', status='offline', public_state='hidden',
    segments=['biotechnology'], partnership_types=['out_licensing'],
    description=T('Venture builder focada em criar empresas de biotecnologia em RNA, engenharia genética e IA/bioinformática. O portfólio inclui a VYRO Biotherapeutics e a FUTR Bio (também neste diretório).',
                  'Venture builder focused on building biotech companies in RNA technology, genetic engineering and AI/bioinformatics. The portfolio includes VYRO Biotherapeutics and FUTR Bio (also in this directory).'),
    projects=[dict(
        id='vesper-builder', type='B',
        platform_type=T('Venture builder — RNA, engenharia genética e IA/bioinformática', 'Venture builder — RNA, genetic engineering and AI/bioinformatics'),
        maturity='pre_operational',
        platform_description=T('Infraestrutura científica compartilhada para criar e acelerar empresas de biotecnologia.',
                               'Shared scientific infrastructure to build and accelerate biotech companies.'),
        technology_tags=['genomics', 'ai_ml'],
        technology_text=T('Engenharia genética; IA; bioinformática; biologia de RNA.', 'Genetic engineering; AI; bioinformatics; RNA biology.'),
        business_models=['licensing'], business_model_text=T('Licenciamento (modelo de empresas investidas).', 'Licensing (portfolio-company model).'),
        traction=T('Parcerias do portfólio incluem Boston Children’s Hospital, Fiocruz, Libbs, Croda e Corteva.',
                   'Portfolio partnerships include Boston Children’s Hospital, Fiocruz, Libbs, Croda and Corteva.'),
        competitive_edge=T('Modelo integrado de venture builder com infraestrutura científica compartilhada e acesso a parceiros estratégicos globais em farma, biotech e agrobiotech.',
                           'Integrated venture-builder model with shared scientific infrastructure and access to global strategic partners across pharma, biotech and agri-biotech.'),
    )])

org(id='vyro', name='Vyro Biotherapeutics', status='provisional', public_state='provisional',
    segments=['biotechnology', 'human_health'], partnership_types=['out_licensing'],
    description=T('Usa um vírus Zika geneticamente modificado como vetor terapêutico para tumores do sistema nervoso central e como plataforma de entrega gênica, aproveitando o tropismo natural do Zika pelo cérebro.',
                  'Uses a genetically modified Zika virus as a therapeutic vector for central nervous system tumors and as a gene-delivery platform, leveraging Zika’s natural tropism for the brain.'),
    projects=[dict(
        id='vyro-zika', type='B',
        platform_type=T('Vetor viral / entrega gênica — Zika modificado para tumores do SNC', 'Viral vector / gene delivery — Modified Zika virus for CNS tumors'),
        maturity='pre_operational',
        platform_description=T('Plataforma de vetor viral atenuado com tropismo pelo sistema nervoso central.',
                               'Attenuated viral-vector platform with central nervous system tropism.'),
        technology_tags=['genomics'],
        technology_text=T('Genômica; engenharia de vetores virais; vírus Zika modificado; entrega gênica direcionada ao SNC.',
                          'Genomics; viral vector engineering; modified Zika virus; CNS-targeted gene delivery.'),
        business_models=['licensing'], business_model_text=T('Licenciamento.', 'Licensing.'),
        traction=T('2 parcerias ativas.', '2 active partnerships.'),
        competitive_edge=T('Atravessa naturalmente a barreira hematoencefálica; tropismo cerebral; alta especificidade em doses baixas; perfil de segurança de plataforma viral atenuada.',
                           'Natural blood-brain-barrier penetration; brain tropism; high specificity at low doses; safety profile of an attenuated viral platform.'),
    )])

org(id='futrbio', name='Futr Bio', status='provisional', public_state='provisional',
    segments=['biotechnology', 'human_health'], partnership_types=['out_licensing'],
    description=T('Desenvolve vacinas de mRNA de nova geração com sequências UTR próprias e reforçadores moleculares que geram respostas imunes mais rápidas e duradouras, potencialmente em dose única e baixa.',
                  'Develops next-generation mRNA vaccines using proprietary UTR sequences and molecular boosters that generate faster, more durable immune responses, potentially in a single low dose.'),
    projects=[dict(
        id='futrbio-mrna', type='B',
        platform_type=T('Engenharia de vacinas de mRNA — Vacinas de nova geração', 'mRNA vaccine engineering — Next-generation vaccines'),
        maturity='pre_operational',
        platform_description=T('Biblioteca própria de UTRs e reforçadores moleculares aplicáveis a diferentes antígenos.',
                               'Proprietary library of UTRs and molecular boosters applicable to different antigens.'),
        technology_tags=['genomics'],
        technology_text=T('Imunologia; virologia; genômica; nanopartículas lipídicas (LNPs); engenharia própria de UTRs.',
                          'Immunology; virology; genomics; lipid nanoparticles (LNPs); proprietary UTR engineering.'),
        business_models=['licensing'], business_model_text=T('Licenciamento.', 'Licensing.'),
        traction=T('4 parcerias ativas.', '4 active partnerships.'),
        competitive_edge=T('UTRs e reforçadores moleculares próprios com cinética imune superior (início mais rápido, maior duração) em doses menores que as vacinas de mRNA convencionais.',
                           'Proprietary UTRs and molecular boosters with superior immune kinetics (faster onset, longer duration) at lower doses than conventional mRNA vaccines.'),
    )])

org(id='huna', name='Huna', status='published', public_state='published', featured=False, size='startup',
    city='São Paulo', state='SP', website='https://www.huna.example',
    segments=['human_health', 'devices_diagnostics'], partnership_types=['vc', 'market_distribution'],
    description=T('Plataforma de IA que identifica padrões em dados clínicos — biomarcadores laboratoriais, genômicos e proteômicos — para oncologia. A primeira aplicação, já operando em escala, usa dados de hemograma para rastrear 5 tipos de câncer.',
                  'AI platform identifying patterns in clinical data — lab, genomic and proteomic biomarkers — for oncology. Its first application, already operational at scale, uses CBC/blood-count data to screen for 5 cancer types.'),
    projects=[dict(
        id='huna-ai', type='B',
        platform_type=T('IA / Biomarcadores clínicos — Rastreamento oncológico', 'AI / Clinical biomarkers — Oncology screening'),
        maturity='partially_operational',
        platform_description=T('Primeira aplicação em operação: rastreamento de 5 tipos de câncer a partir de hemogramas de rotina.',
                               'First application in operation: screening for 5 cancer types from routine blood counts.'),
        technology_tags=['ai_ml'],
        technology_text=T('IA/ML que processa grandes volumes de dados clínicos estruturados e não estruturados, com foco em biomarcadores laboratoriais e de patologia.',
                          'AI/ML processing large volumes of structured and unstructured clinical data, focused on routine lab and pathology biomarkers.'),
        business_models=['saas', 'service'],
        business_model_text=T('Modelo híbrido: receita recorrente por uso (vidas/análises processadas) com camada de resultado (AI-as-a-Service).',
                              'Hybrid model: usage-based recurring revenue (lives/analyses processed) with an outcomes layer (AI-as-a-Service).'),
        traction=T('Mais de 10 clientes na saúde privada; projetos de saúde pública em Barretos e na SES/RJ. Parcerias com Fleury, Sabin, Hermes Pardini e Hospital de Amor. Base própria de mais de 5 milhões de pacientes.',
                   '10+ operational clients in private healthcare; public-health projects in Barretos and SES/RJ. Partnerships with Fleury, Sabin, Hermes Pardini and Hospital de Amor. Proprietary dataset of 5M+ patients.'),
        competitive_edge=T('Especialização em oncologia combinada a IA aplicada a biomarcadores; base de 20 anos de dados longitudinais; primeira aplicação 4,5 vezes mais eficiente que o rastreamento convencional em estudos prospectivos.',
                           'Deep oncology specialization combined with AI applied to biomarkers; 20 years of longitudinal data; first application 4.5x more efficient than conventional screening in prospective studies.'),
        rounds=[rnd('seed', ms(2026, s=2), 5000000, 'Escala comercial e novos biomarcadores', 'Commercial scale-up and new biomarkers')],
        use_of_funds=T('Expansão comercial e ampliação para dados genômicos e proteômicos.', 'Commercial expansion and extension to genomic and proteomic data.'),
        raised=[raised('vc', 1500000), raised('angel', 500000)],
    )])

# ---------------------------------------------------------------- Profile D
org(id='croplabs', name='Crop Labs', status='published', public_state='published', featured=False, size='medium',
    city='Campinas', state='SP', website='https://www.croplabs.example',
    segments=['cro'], partnership_types=['infrastructure_investment', 'market_distribution'],
    description=T('A Crop Labs é uma CRO estabelecida que oferece controle de qualidade com certificação BPL e testes pré-clínicos para clientes farmacêuticos e de bens de consumo.',
                  'Crop Labs is an established CRO offering GLP-certified quality control and pre-clinical testing services for pharmaceutical and consumer-goods clients.'),
    projects=[
        dict(id='croplabs-pharma', type='D',
             summary=T('Controle de qualidade e testes pré-clínicos BPL para a indústria farmacêutica.', 'GLP quality control and pre-clinical testing for the pharmaceutical industry.'),
             services=['quality_control', 'analytical', 'preclinical', 'bpl'],
             services_text=T('Controle de qualidade de IFAs, matérias-primas, injetáveis e sintéticos, e microbiologia de áreas produtivas. Testes pré-clínicos sob BPL (modelos in vitro).',
                             'Quality control of APIs, raw materials, injectable and synthetic products, and production-area microbiology. Pre-clinical testing under GLP (in vitro models).'),
             therapeutic_areas=['other'],
             scope_text=T('IFAs; injetáveis acabados; produtos sintéticos.', 'APIs; finished injectable products; synthetic products.'),
             models=T('In vitro (pré-clínico).', 'In vitro (pre-clinical).'),
             certifications=['reblas', 'anvisa', 'bpl'], certificate_numbers='BPL nº 0082 (INMETRO)',
             client_count=42, client_profiles=['national_pharma', 'multinational'],
             revenue=rev(600000, 2025), exports=dict(pct=12, destinations=['north_america', 'europe', 'latin_america']),
             investment_types=['expansion'], investment_range=dict(min=1000000, max=3000000),
             target_markets=['north_america', 'europe', 'latin_america']),
        dict(id='croplabs-consumer', type='D',
             summary=T('Ensaios microbiológicos e analíticos para saneantes e cosméticos.', 'Microbiological and analytical testing for sanitizers and cosmetics.'),
             services=['analytical', 'quality_control'],
             services_text=T('Ensaios microbiológicos e analíticos para saneantes e cosméticos.', 'Microbiological and analytical testing for sanitizers and cosmetics.'),
             therapeutic_areas=['consumer_goods'],
             scope_text=T('Bens de consumo (saneantes, cosméticos).', 'Consumer goods (sanitizers, cosmetics).'),
             certifications=['reblas', 'anvisa'],
             client_profiles=['national_pharma'],
             investment_types=['expansion', 'strategic_partner'],
             target_markets=['latin_america']),
    ])

org(id='ionvet', name='IonVet', logo='assets/logos/ionvet.jpg', status='in_review', public_state='provisional',
    segments=['cro', 'animal_health'], partnership_types=['infrastructure_investment', 'market_distribution'],
    description=T('A IonVet é uma CRO estabelecida que presta serviços analíticos e de pesquisa — metabolômica, validação de biomarcadores e apoio a P&D — para saúde animal e agronegócio.',
                  'IonVet is an established CRO providing analytical and research services — metabolomics, biomarker validation and R&D support — for animal health and agribusiness clients.'),
    projects=[dict(
        id='ionvet-cro', type='D',
        services=['analytical', 'preclinical'],
        services_text=T('Metabolômica de alta resolução; identificação e validação de biomarcadores; caracterização biológica de produtos e ingredientes; desenvolvimento e validação de métodos analíticos; nutrição de precisão; apoio a P&D veterinário.',
                        'High-resolution metabolomics; biomarker identification and validation; biological characterization of products and ingredients; analytical method development and validation; precision nutrition; veterinary R&D support.'),
        therapeutic_areas=['animal_health', 'infectious_diseases', 'immunology'],
        scope_text=T('Saúde animal; medicina veterinária preventiva; reprodução e nutrição animal; saúde intestinal; bem-estar animal.',
                     'Animal health; preventive veterinary medicine; animal reproduction and nutrition; gut health; animal welfare.'),
        models=T('Bovinos, suínos, aves, equinos, ovinos, caprinos, cães, gatos, peixes e outras espécies.',
                 'Bovine, swine, poultry, equine, ovine, caprine, canine, feline, fish and other species.'),
        partner_sites=['USP', 'UNESP', 'UNICAMP', 'Embrapa'],
        client_count=18, client_profiles=['national_pharma', 'startups'],
        revenue=rev(828745, 2025),
        investment_types=['expansion', 'strategic_partner'],
        target_markets=['north_america', 'europe', 'latin_america'],
    )])

# ---------------------------------------------------------------- Profile E
org(id='embrapa', name='Embrapa', status='published', public_state='published', featured=True, size='large',
    city='Brasília', state='DF', website='https://www.embrapa.br',
    segments=['biodiversity_bioeconomy', 'biotechnology', 'animal_health'], partnership_types=['co_development', 'infrastructure_investment'],
    description=T('Maior instituição pública de pesquisa agropecuária do Brasil, com 43 unidades de pesquisa e laboratórios no país, que desenvolve e licencia tecnologias em genômica avançada, biologia sintética e edição de cultivares por CRISPR.',
                  'Brazil’s largest public agricultural research institution, with 43 research and laboratory units nationwide, developing and licensing technologies in advanced genomics, synthetic biology and CRISPR-based crop editing.'),
    projects=[
        dict(id='embrapa-genomics', type='E',
             summary=T('Genômica avançada, biologia sintética e bioprospecção com 43 unidades de pesquisa.', 'Advanced genomics, synthetic biology and bioprospecting across 43 research units.'),
             institution_type=T('Instituição pública de pesquisa agropecuária — Genômica e biodiversidade', 'Public agricultural research — Genomics and biodiversity'),
             product_portfolio=[(T('Genômica', 'Genomics'), T('Genômica avançada com edição de cultivares por CRISPR.', 'Advanced genomics with CRISPR-based crop editing.')),
                                (T('Bioinsumos', 'Bioinputs'), T('Biopesticidas e bioinsumos.', 'Biopesticides and bioinputs.')),
                                (T('Cultivares', 'Crop varieties'), T('Cultivares resilientes ao clima.', 'Climate-resilient crop varieties.'))],
             production_capacity=T('43 unidades de pesquisa e laboratórios; plantas-piloto multiusuário de biologia sintética, metabolômica, genômica e bioprospecção.',
                                   '43 research and laboratory units; multi-user pilot plants for synthetic biology, metabolomics, genomics and bioprospecting.'),
             export_markets=['latin_america', 'north_america', 'africa', 'asia'],
             export_markets_text=T('Ativos tecnológicos e cooperação técnica com mais de 30 países (foco na CPLP).', 'Technology assets and technical cooperation with 30+ countries (CPLP focus).'),
             certifications=['anvisa', 'other'],
             partnership_interests=[(T('Biotecnologia avançada', 'Advanced biotechnology'), T('Co-desenvolvimento em edição genômica, cultivares resilientes e biologia sintética.', 'Co-development in genomic editing, resilient cultivars and synthetic biology.')),
                                    (T('Interface saúde/farma', 'Health/pharma interface'), T('Compostos naturais e bioprospecção de insumos farmacêuticos.', 'Natural compounds and bioprospecting for pharmaceutical inputs.')),
                                    (T('Agricultura digital', 'Digital agriculture'), T('IA para monitoramento de pragas e doenças.', 'AI for pest and disease monitoring.'))],
             partnership_models=['co_development', 'technology_transfer', 'licensing'],
             expansion_projects=T('Modernização de plantas-piloto e laboratórios multiusuário de biologia sintética, metabolômica, genômica e bioprospecção.',
                                  'Modernization of pilot plants and multi-user labs for synthetic biology, metabolomics, genomics and bioprospecting.'),
             investment_range=dict(min=100000, max=10000000),
             investment_description=T('Projetos de co-desenvolvimento e infraestrutura laboratorial.', 'Co-development projects and lab infrastructure.')),
        dict(id='embrapa-bioinputs', type='B',
             summary=T('Plataforma de bioinsumos microbianos para saúde vegetal e animal.', 'Microbial bioinputs platform for plant and animal health.'),
             platform_type=T('Plataforma de bioinsumos microbianos', 'Microbial bioinputs platform'),
             maturity='partially_operational',
             platform_description=T('Coleção de microrganismos e processos de formulação para bioinsumos, disponível para licenciamento e co-desenvolvimento.',
                                    'Microorganism collection and formulation processes for bioinputs, available for licensing and co-development.'),
             technology_tags=['fermentation', 'genomics'],
             technology_text=T('Coleção de microrganismos; fermentação; formulação de bioinsumos.', 'Microorganism collection; fermentation; bioinput formulation.'),
             business_models=['licensing'],
             business_model_text=T('Licenciamento de tecnologia e co-desenvolvimento com empresas.', 'Technology licensing and co-development with companies.'),
             traction=T('Tecnologias licenciadas a empresas brasileiras de bioinsumos.', 'Technologies licensed to Brazilian bioinput companies.'),
             competitive_edge=T('Uma das maiores coleções de microrganismos da América Latina, com dados de campo de décadas.',
                                'One of Latin America’s largest microorganism collections, with decades of field data.')),
    ])

org(id='biomanguinhos', name='Bio-Manguinhos / Fiocruz', status='published', public_state='published', featured=True, size='large',
    city='Rio de Janeiro', state='RJ', website='https://www.bio.fiocruz.br',
    segments=['pharmaceutical', 'biotechnology', 'human_health', 'devices_diagnostics'], partnership_types=['co_development', 'joint_venture'],
    description=T('Instituição pública vinculada ao Ministério da Saúde e uma das maiores produtoras de imunobiológicos da América Latina, construindo plataformas de terapias avançadas em RNA, CAR-T e terapia gênica.',
                  'Public institution under Brazil’s Ministry of Health and one of Latin America’s largest immunobiological producers, building advanced-therapy platforms in RNA, CAR-T and gene therapy.'),
    projects=[dict(
        id='biomanguinhos-main', type='E',
        institution_type=T('Produtora pública — Vacinas, biofármacos e diagnósticos', 'Public producer — Vaccines, biopharmaceuticals and diagnostics'),
        product_portfolio=[(T('Vacinas', 'Vaccines'), T('11 vacinas em plataformas virais e bacterianas.', '11 vaccines on viral and bacterial platforms.')),
                           (T('Biofármacos', 'Biopharmaceuticals'), T('10 biofármacos, entre eles adalimumabe, infliximabe, trastuzumabe e rituximabe.', '10 biopharmaceuticals, including adalimumab, infliximab, trastuzumab and rituximab.')),
                           (T('Diagnósticos', 'Diagnostics'), T('40 kits de diagnóstico.', '40 diagnostic kits.'))],
        production_capacity=T('Vacinas: 150 milhões de doses/ano. Biofármacos: 9 milhões de frascos/seringas por ano.',
                              'Vaccines: 150 million doses/year. Biopharmaceuticals: 9 million vials/syringes per year.'),
        export_markets=['latin_america', 'africa', 'asia'],
        export_markets_text=T('16 milhões de doses/ano de vacina de febre amarela para 75 países via OPAS.', '16 million doses/year of yellow fever vaccine to 75 countries via PAHO.'),
        certifications=['anvisa', 'who', 'who_pq'],
        partnership_interests=[(T('Plataforma de RNA', 'RNA platform'), T('Desenvolvimento conjunto de vacinas e terapias de RNA.', 'Joint development of RNA vaccines and therapies.')),
                               (T('Biossimilares', 'Biosimilars'), T('Transferência de tecnologia de biossimilares.', 'Biosimilar technology transfer.')),
                               (T('CAR-T in vivo', 'In vivo CAR-T'), T('Terapias celulares avançadas.', 'Advanced cell therapies.'))],
        partnership_models=['co_development', 'technology_transfer'],
        expansion_projects=T('Terapias avançadas — plataformas de RNA, CAR-T in vivo e terapia gênica.', 'Advanced therapies — RNA, in vivo CAR-T and gene-therapy platforms.'),
        investment_range=dict(min=10000000, max=50000000),
    )])
