"""FICTITIOUS organizations, added only to bring the demo close to the volume in spec 1
(32 organizations, 38 projects) and to cover profiles C and F, which the prototype did not have.
Names, people and figures are invented. Real data will come from the Google Forms import.
"""
from helpers import T, ms, rnd, raised, rev

ORGS = []


def org(**kw):
    kw['fictitious'] = True
    ORGS.append(kw)
    return kw


# An organization with 4 projects (the spec's Aché case), each with a different profile.
org(id='aurora', name='Aurora Farma', status='published', public_state='published', featured=True, size='large',
    city='Guarulhos', state='SP', website='https://www.aurorafarma.example',
    segments=['pharmaceutical', 'apis', 'human_health'], partnership_types=['out_licensing', 'co_development', 'joint_venture', 'market_distribution'],
    description=T('Farmacêutica brasileira de capital nacional com 40 anos de mercado, portfólio de genéricos e inovação incremental, e unidades de P&D, produção de IFAs e embalagens especiais.',
                  'Brazilian-owned pharmaceutical company with 40 years in the market, a portfolio of generics and incremental innovation, and R&D, API and specialty-packaging units.'),
    leadership=[
        dict(name='Helena Prado', role=T('Presidente', 'CEO'), experience=T('25 anos na indústria farmacêutica, ex-diretora comercial para a América Latina.', '25 years in pharma; former Latin America commercial director.')),
        dict(name='Marcos Tavares', role=T('Vice-presidente de inovação', 'VP Innovation'), experience=T('Liderou 12 lançamentos de novos produtos no Brasil.', 'Led 12 new product launches in Brazil.')),
        dict(name='Luiza Fontes', role=T('Diretora industrial', 'Industrial Director'), experience=T('Responsável por três plantas certificadas pela ANVISA e pela EMA.', 'Runs three plants certified by ANVISA and EMA.')),
        dict(name='Pedro Albuquerque', role=T('Diretor financeiro', 'CFO'), experience=T('Ex-banco de investimento, especialista em M&A no setor de saúde.', 'Former investment banker, healthcare M&A specialist.')),
    ],
    projects=[
        dict(id='aurora-au101', type='A',
             summary=T('AU-101: anti-inflamatório oral de liberação prolongada para artrite reumatoide, em Fase II.', 'AU-101: extended-release oral anti-inflammatory for rheumatoid arthritis, in Phase II.'),
             segment=T('Reumatologia — Anti-inflamatório oral de liberação prolongada', 'Rheumatology — Extended-release oral anti-inflammatory'),
             trl=6, regulatory_phase='phase_2', lead_product_name='AU-101',
             lead_product_moa=T('Inibidor seletivo de JAK1 em formulação de liberação prolongada, com dose única diária.', 'Selective JAK1 inhibitor in an extended-release formulation, once daily.'),
             pipeline=[('AU-102', T('Artrite psoriásica', 'Psoriatic arthritis'))],
             patents_filed=T('Formulação depositada no BR, US e EP.', 'Formulation filed in BR, US and EP.'), fto='yes',
             milestones=[ms(2025, s=2, pt='Conclusão da Fase I', en='Phase I completed'),
                         ms(2026, m=11, pt='Primeiro paciente na Fase II', en='First patient in Phase II'),
                         ms(2028, s=1, pt='Resultados da Fase II', en='Phase II results')],
             rounds=[rnd('other', ms(2026, s=2), 15000000, 'Co-desenvolvimento da Fase II', 'Phase II co-development')],
             use_of_funds=T('Estudo de Fase II em 12 centros no Brasil e na Argentina.', 'Phase II study in 12 sites in Brazil and Argentina.'),
             raised=[raised('own_resources', 8000000), raised('finep', 2500000)],
             revenue=rev(310000000, 2025),
             gtm_models=['co_development', 'out_licensing'],
             gtm_text=T('Co-desenvolvimento para mercados fora da América Latina.', 'Co-development for markets outside Latin America.'),
             target_markets=['brazil', 'latin_america', 'europe']),
        dict(id='aurora-au201', type='A',
             summary=T('AU-201: biossimilar de anticorpo monoclonal para oncologia, em fase pré-clínica.', 'AU-201: monoclonal antibody biosimilar for oncology, pre-clinical.'),
             segment=T('Oncologia — Biossimilar de anticorpo monoclonal', 'Oncology — Monoclonal antibody biosimilar'),
             trl=4, regulatory_phase='preclinical', lead_product_name='AU-201',
             lead_product_moa=T('Anticorpo anti-HER2 biossimilar.', 'Anti-HER2 biosimilar antibody.'),
             milestones=[ms(2027, s=2, pt='Comparabilidade analítica concluída', en='Analytical comparability completed')],
             rounds=[rnd('other', ms(2027, s=1), 8000000, 'Desenvolvimento analítico e clínico', 'Analytical and clinical development')],
             use_of_funds=T('Comparabilidade analítica e estudo clínico de equivalência.', 'Analytical comparability and clinical equivalence study.'),
             raised=[raised('own_resources', 3000000)],
             gtm_models=['direct_sales', 'partnership_distribution'],
             gtm_text=T('Venda direta no Brasil e parceiros na América Latina.', 'Direct sales in Brazil and partners in Latin America.'),
             target_markets=['brazil', 'latin_america']),
        dict(id='aurora-cdmo', type='C',
             summary=T('Unidade de CDMO para formulação e fabricação de sólidos orais e injetáveis.', 'CDMO unit for formulation and manufacturing of oral solids and injectables.'),
             services=['process_development', 'formulation', 'manufacturing', 'analytical'],
             services_text=T('Desenvolvimento de processo, formulação, escalonamento e fabricação comercial de sólidos orais e injetáveis.', 'Process development, formulation, scale-up and commercial manufacturing of oral solids and injectables.'),
             molecule_types=['small_molecules', 'apis'],
             capacity_scales=['pilot', 'commercial'], utilization_pct=68,
             capacity_text=T('2 bilhões de comprimidos/ano e 30 milhões de ampolas/ano.', '2 billion tablets/year and 30 million ampoules/year.'),
             certifications=['gmp', 'anvisa', 'ema'],
             client_count=35, client_profiles=['startups', 'national_pharma', 'multinational'],
             revenue=rev(42000000, 2025), exports=dict(amount_usd=6500000, year=2025),
             expansion_plan=T('Nova linha de injetáveis estéreis em 2027.', 'New sterile injectables line in 2027.'),
             investment_types=['jv', 'infrastructure_expansion'], investment_range=dict(min=10000000, max=25000000),
             target_markets=['brazil', 'latin_america', 'africa']),
        dict(id='aurora-packaging', type='F',
             summary=T('Embalagens farmacêuticas especiais e insumos para a indústria.', 'Specialty pharmaceutical packaging and inputs for the industry.'),
             products=[T('Blísteres de alta barreira', 'High-barrier blisters'), T('Frascos de vidro tipo I', 'Type I glass vials'), T('Excipientes', 'Excipients')],
             products_text=T('Embalagens primárias e secundárias para medicamentos, com rastreabilidade.', 'Primary and secondary packaging for medicines, with traceability.'),
             markets_served=['brazil', 'latin_america'],
             markets_text=T('Farmacêuticas nacionais e multinacionais instaladas no Brasil.', 'Brazilian and multinational pharma companies operating in Brazil.'),
             certifications=['iso', 'gmp'],
             market_share=dict(pct=14, segment=T('Blísteres farmacêuticos no Brasil', 'Pharmaceutical blisters in Brazil')),
             revenue=rev(18000000, 2025), exports=dict(pct=8, destinations=['latin_america']),
             expansion_strategy=T('Ampliar exportações para o Mercosul.', 'Expand exports to Mercosur.'),
             partnership_models=['jv', 'distribution'], investment_range=dict(min=2000000, max=6000000)),
    ])

# An institution with 2 projects (the spec's Butantan case).
org(id='vitalbio', name='Instituto Vital Bio', status='published', public_state='published', size='large',
    city='Belo Horizonte', state='MG', website='https://www.vitalbio.example',
    segments=['biotechnology', 'human_health', 'pharmaceutical'], partnership_types=['co_development', 'joint_venture'],
    description=T('Instituto público estadual de pesquisa e produção de soros, vacinas e biofármacos, com centro de desenvolvimento de vacinas de mRNA.',
                  'State-owned institute for research and production of sera, vaccines and biopharmaceuticals, with an mRNA vaccine development center.'),
    projects=[
        dict(id='vitalbio-production', type='E',
             summary=T('Produção de soros e vacinas para o SUS, com interesse em transferência de tecnologia.', 'Production of sera and vaccines for the public health system, seeking technology transfer.'),
             institution_type=T('Instituto público — Soros, vacinas e biofármacos', 'Public institute — Sera, vaccines and biopharmaceuticals'),
             product_portfolio=[(T('Soros', 'Sera'), T('8 soros hiperimunes.', '8 hyperimmune sera.')), (T('Vacinas', 'Vaccines'), T('4 vacinas do calendário nacional.', '4 national-schedule vaccines.'))],
             production_capacity=T('60 milhões de doses/ano.', '60 million doses/year.'),
             certifications=['anvisa', 'who'],
             partnership_interests=[(T('Vacinas combinadas', 'Combination vaccines'), T('Transferência de tecnologia para produção local.', 'Technology transfer for local production.'))],
             partnership_models=['technology_transfer', 'co_development'],
             investment_range=dict(min=5000000, max=20000000)),
        dict(id='vitalbio-mrna', type='A',
             summary=T('Vacina de mRNA contra dengue em fase pré-clínica.', 'Pre-clinical mRNA dengue vaccine.'),
             segment=T('Doenças infecciosas — Vacina de mRNA contra dengue', 'Infectious diseases — mRNA dengue vaccine'),
             trl=4, regulatory_phase='preclinical', lead_product_name='VB-DEN1',
             lead_product_moa=T('mRNA tetravalente codificando antígenos dos quatro sorotipos.', 'Tetravalent mRNA encoding antigens of the four serotypes.'),
             milestones=[ms(2027, s=1, pt='Estudos de toxicologia', en='Toxicology studies')],
             rounds=[rnd('other', ms(2027, s=1), 12000000, 'Pré-clínico e Fase I', 'Pre-clinical and Phase I')],
             use_of_funds=T('Lotes clínicos e estudo de Fase I.', 'Clinical batches and Phase I study.'),
             raised=[raised('bndes', 4000000)],
             gtm_models=['co_development'], gtm_text=T('Co-desenvolvimento com parceiro internacional.', 'Co-development with an international partner.'),
             target_markets=['brazil', 'latin_america', 'asia']),
    ])

org(id='biofactor', name='BioFactor CDMO', status='published', public_state='published', size='medium',
    city='Curitiba', state='PR', website='https://www.biofactor.example',
    segments=['biotechnology', 'pharmaceutical'], partnership_types=['joint_venture', 'infrastructure_investment'],
    description=T('CDMO de biológicos com plantas de cultivo celular e fermentação microbiana, do desenvolvimento de processo ao lote clínico.',
                  'Biologics CDMO with cell-culture and microbial fermentation plants, from process development to clinical batches.'),
    projects=[dict(id='biofactor-main', type='C',
                   services=['process_development', 'manufacturing', 'analytical'],
                   services_text=T('Desenvolvimento de linhagens, processo upstream e downstream, lotes clínicos GMP.', 'Cell-line development, upstream and downstream processing, GMP clinical batches.'),
                   molecule_types=['biologics', 'antibodies', 'vaccines'],
                   capacity_scales=['laboratory', 'pilot'], utilization_pct=74,
                   capacity_text=T('Biorreatores de 50 L a 1.000 L.', 'Bioreactors from 50 L to 1,000 L.'),
                   certifications=['gmp', 'anvisa', 'iso'],
                   client_count=14, client_profiles=['startups', 'national_pharma'],
                   revenue=rev(9500000, 2025), exports=dict(none=True),
                   expansion_plan=T('Biorreator de 2.000 L para fabricação comercial.', '2,000 L bioreactor for commercial manufacturing.'),
                   investment_types=['pe', 'infrastructure_expansion', 'strategic_partner'], investment_range=dict(min=8000000, max=15000000),
                   target_markets=['brazil', 'latin_america', 'north_america'])])

org(id='nexa', name='Nexa Insumos', status='published', public_state='published', size='medium',
    city='Jundiaí', state='SP', website='https://www.nexainsumos.example',
    segments=['apis', 'pharmaceutical'], partnership_types=['market_distribution', 'joint_venture'],
    description=T('Fabricante de excipientes e intermediários farmacêuticos de alta pureza, com laboratório próprio de controle de qualidade.',
                  'Manufacturer of high-purity pharmaceutical excipients and intermediates, with an in-house quality-control lab.'),
    projects=[dict(id='nexa-main', type='F',
                   products=[T('Excipientes de celulose', 'Cellulose excipients'), T('Intermediários de síntese', 'Synthesis intermediates')],
                   products_text=T('Excipientes e intermediários para sólidos orais, com DMF registrado.', 'Excipients and intermediates for oral solids, with registered DMF.'),
                   markets_served=['brazil', 'latin_america', 'europe'],
                   certifications=['iso', 'gmp', 'dmf'],
                   revenue=rev(26000000, 2025), exports=dict(pct=22, destinations=['latin_america', 'europe']),
                   expansion_strategy=T('Nova planta de intermediários em 2028.', 'New intermediates plant in 2028.'),
                   partnership_models=['distribution', 'jv'], investment_range=dict(min=5000000, max=12000000))])

org(id='amazonia', name='Amazônia Bioativos', status='published', public_state='published', size='startup',
    city='Manaus', state='AM', website='https://www.amazoniabioativos.example',
    segments=['biodiversity_bioeconomy', 'apis'], partnership_types=['market_distribution', 'vc'],
    description=T('Produz extratos padronizados e ativos de origem amazônica para as indústrias farmacêutica e cosmética, com cadeia rastreável e repartição de benefícios.',
                  'Produces standardized Amazonian extracts and actives for the pharmaceutical and cosmetics industries, with a traceable supply chain and benefit sharing.'),
    projects=[dict(id='amazonia-main', type='F',
                   products=[T('Extratos padronizados', 'Standardized extracts'), T('Óleos vegetais', 'Vegetable oils')],
                   products_text=T('12 extratos com marcadores químicos definidos e 5 óleos vegetais.', '12 extracts with defined chemical markers and 5 vegetable oils.'),
                   markets_served=['brazil', 'europe', 'north_america'],
                   certifications=['iso'],
                   revenue=rev(1200000, 2025),
                   partnership_models=['distribution', 'pe'], investment_range=dict(min=1000000, max=3000000))])

org(id='veritas', name='Veritas Clinical CRO', status='in_review', public_state='hidden', size='medium',
    city='Porto Alegre', state='RS', website='https://www.veritascro.example',
    segments=['cro'], partnership_types=['infrastructure_investment'],
    description=T('CRO clínica com rede de centros de pesquisa no Sul do Brasil, especializada em estudos de Fase I a IV.',
                  'Clinical CRO with a network of research sites in southern Brazil, specialized in Phase I–IV studies.'),
    projects=[dict(id='veritas-main', type='D',
                   services=['clinical_phase_1_4'],
                   services_text=T('Condução de estudos de Fase I a IV, monitoria e gestão de dados.', 'Conduct of Phase I–IV studies, monitoring and data management.'),
                   therapeutic_areas=['oncology', 'cardiovascular', 'metabolic'],
                   certifications=['bpc', 'anvisa'],
                   partner_sites=['Hospital Moinhos (fictício)', 'Centro Clínico Sul (fictício)'],
                   investment_types=['expansion'], target_markets=['brazil', 'latin_america'])])

org(id='synthera', name='Synthera Bio', status='awaiting_validation', public_state='hidden', size='startup',
    segments=['biotechnology'], partnership_types=['vc'],
    description=T('Startup de peptídeos sintéticos para doenças raras.', 'Synthetic-peptide startup for rare diseases.'),
    projects=[dict(id='synthera-main', type='A',
                   segment=T('Doenças raras — Peptídeos sintéticos', 'Rare diseases — Synthetic peptides'),
                   trl=3, regulatory_phase='preclinical', target_markets=['brazil'])])

org(id='lumina', name='Lumina Diagnostics', status='published', public_state='published', size='startup',
    city='Florianópolis', state='SC', website='https://www.luminadx.example',
    segments=['devices_diagnostics', 'human_health'], partnership_types=['vc', 'market_distribution'],
    description=T('Plataforma de diagnóstico molecular point-of-care com chip microfluídico e leitura por smartphone.',
                  'Point-of-care molecular diagnostics platform with a microfluidic chip and smartphone readout.'),
    projects=[dict(id='lumina-main', type='B',
                   platform_type=T('Diagnóstico molecular point-of-care', 'Point-of-care molecular diagnostics'),
                   maturity='partially_operational',
                   platform_description=T('Cartucho microfluídico descartável que realiza amplificação isotérmica em 20 minutos.', 'Disposable microfluidic cartridge running isothermal amplification in 20 minutes.'),
                   technology_tags=['microfluidics', 'biosensors'],
                   technology_text=T('Amplificação isotérmica; microfluídica; leitura óptica por smartphone.', 'Isothermal amplification; microfluidics; smartphone optical readout.'),
                   business_models=['equipment', 'consumables'],
                   business_model_text=T('Leitor em comodato e venda de cartuchos.', 'Reader placement and cartridge sales.'),
                   traction=T('Pilotos em 6 laboratórios; registro ANVISA classe III em análise.', 'Pilots in 6 labs; ANVISA class III registration under review.'),
                   revenue=rev(150000, 2025),
                   competitive_edge=T('Custo por teste 70% menor que o PCR de bancada.', 'Cost per test 70% lower than benchtop PCR.'),
                   rounds=[rnd('seed', ms(2026, s=2), 3000000, 'Registro e escala de produção', 'Registration and production scale-up')],
                   use_of_funds=T('Registro ANVISA e linha de produção de cartuchos.', 'ANVISA registration and cartridge production line.'),
                   raised=[raised('fapesp', 400000), raised('angel', 350000)])])

org(id='pharmaplex', name='Pharmaplex Industrial', status='provisional', public_state='provisional', size='large',
    segments=['pharmaceutical', 'apis'], partnership_types=['joint_venture', 'market_distribution'],
    description=T('Produtora de medicamentos genéricos e IFAs com três plantas industriais e exportação para a América Latina.',
                  'Producer of generic medicines and APIs with three industrial plants and exports to Latin America.'),
    projects=[dict(id='pharmaplex-main', type='E',
                   institution_type=T('Produtora de grande porte — Genéricos e IFAs', 'Large producer — Generics and APIs'),
                   product_portfolio=[(T('Genéricos', 'Generics'), T('180 registros de genéricos.', '180 generic registrations.')),
                                      (T('IFAs', 'APIs'), T('12 IFAs produzidos internamente.', '12 APIs produced in-house.'))],
                   production_capacity=T('3 plantas, 1,5 bilhão de unidades/ano.', '3 plants, 1.5 billion units/year.'),
                   certifications=['anvisa', 'other'],
                   partnership_interests=[(T('IFAs oncológicos', 'Oncology APIs'), T('Transferência de tecnologia para produção local.', 'Technology transfer for local production.'))],
                   partnership_models=['jv', 'technology_transfer'])])
